checks:
    python:
        code_rating: true
        duplicate_code: true
filter:
    excluded_paths:
        - '*/tests/*'
        - '*/external/*'
        {%- if cookiecutter.use_versioneer == 'y' %}
        - '*/versioneer.py'
        {% else %}
        - '*/{{ cookiecutter.project_name }}/_version.py'
        {%- endif %}
