{%- raw %}{%{% endraw %} set name = "{{ cookiecutter.repo_name }}" {% raw %}%}{% endraw %}
{%- raw %}
{% set version = "0.1" %}
{% set hash_type = "sha256" %}
{% set hash = "" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  fn: {{ name }}-{{ version }}.tar.gz
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  {{ hash_type }}: {{ hash }}
{% endraw %}
build:
  number: 0
  script: python setup.py install --single-version-externally-managed --record=record.txt

requirements:
  build:
    - python
    - setuptools

  run:
    - python
    - spyder >=3.2
    - qtpy

test:
  imports:
    - {{ cookiecutter.project_name }}

about:
  home: https://github.com/{{ cookiecutter.github_username }}/{{ cookiecutter.repo_name }}
  license: MIT
  license_family: MIT
  license_file: LICENSE.txt
  summary: '{{ cookiecutter.description }}'
  description: |
    {{ cookiecutter.description }}
  dev_url: https://github.com/{{ cookiecutter.github_username }}/{{ cookiecutter.repo_name }}

extra:
  recipe-maintainers:
    - {{ cookiecutter.github_username }}
